replicaCount: 2
image:
  repository: adishjain1107/nginx-custom
  tag: latest
service:
  type: NodePort
  port: 80
resources: {}
pvc:
  name: wp-local-pvc

exporter:
  enabled: true
  tag: latest
  scrapePath: /stub_status
