apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type }}
  ports:
      - port: {{ .Values.service.port }}
        targetPort: 80
        name: web
      - port: 9113
        targetPort: 9113
        name: nginx-exporter
  selector:
    app: nginx
