replicaCount: 2
image:
  repository: wordpress
  tag: latest
service:
  type: ClusterIP
  port: 80
resources: {}
pvc:
  name: wp-local-pvc
mysqlDatabase: "wordpress"
mysqlUser: "wpuser"
mysqlPassword: "wppassword"
