apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  mysql-root-password: {{ .Values.mysqlRootPassword | quote }}
  mysql-user: {{ .Values.mysqlUser | quote }}
  mysql-password: {{ .Values.mysqlPassword | quote }}
  mysql-database: {{ .Values.mysqlDatabase | quote }}
