apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: {{ .Values.service.type }}
  ports:
      - port: {{ .Values.service.port }}
        targetPort: 3306
        name: mysql
      - port: 9104
        targetPort: 9104
        name: mysqld-exporter
  selector:
    app: mysql
